import bcrypt from "bcryptjs";
import { Router } from "express";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { z } from "zod";
import { env } from "../config/env";
import { clearSessionCookie, createSession, CUSTOMER_COOKIE, noStore, randomToken, readCookie, revokeSessions, setSessionCookie, tokenHash } from "../auth/sessions";
import { withTransaction, queryRows } from "../db/pool";
import { requireCustomer } from "../middleware/customerAuth";
import { requireSameOrigin } from "../middleware/csrf";
import { isMailConfigured, sendEmailChangeEmail, sendRegistrationNotification, sendResetEmail, sendVerificationEmail } from "../services/mailService";
import { ApiError } from "../utils/errors";
import { sanitizeEmail, sanitizePlainText } from "../utils/sanitize";

const password = z.string().min(12,"Password is too short").max(128).regex(/[a-z]/,"Password is too weak").regex(/[A-Z]/,"Password is too weak").regex(/\d/,"Password is too weak").regex(/[^A-Za-z0-9]/,"Password is too weak");
const registration = z.object({ email:z.string().email().max(190), password, firstName:z.string().min(1).max(80), lastName:z.string().min(1).max(80), phone:z.string().max(40).optional() }).strict();
const credentials=z.object({email:z.string().email().max(190),password:z.string().min(1).max(128)}).strict();
const tokenPayload=z.object({token:z.string().min(32).max(256)}).strict();
const profile=z.object({firstName:z.string().min(1).max(80).optional(),lastName:z.string().min(1).max(80).optional(),phone:z.string().max(40).nullable().optional(),address:z.string().max(240).nullable().optional(),subdistrict:z.string().max(120).nullable().optional(),district:z.string().max(120).nullable().optional(),province:z.string().max(120).nullable().optional(),postalCode:z.string().max(20).nullable().optional()}).strict();
const preferences=z.object({notificationFrequency:z.enum(["realtime","daily","none"]),marketingPreference:z.boolean()}).strict();
const actionToken=z.object({token:z.string().min(32).max(256)}).strict();
const reset=z.object({token:z.string().min(32).max(256),password}).strict();
const changePassword=z.object({currentPassword:z.string().min(1).max(128),newPassword:password}).strict();
const changeEmail=z.object({currentPassword:z.string().min(1).max(128),newEmail:z.string().email().max(190)}).strict();
const deleteAccount=z.object({currentPassword:z.string().min(1).max(128),confirmation:z.literal("DELETE")}).strict();
type CustomerRow=RowDataPacket & {id:number;email:string;password_hash:string;first_name:string;last_name:string;phone:string|null;address:string|null;subdistrict:string|null;district:string|null;province:string|null;postal_code:string|null;status:"PENDING_VERIFICATION"|"ACTIVE"|"DISABLED"|"DELETED";email_verified_at:string|null;last_login_at:string|null;notification_frequency:"realtime"|"daily"|"none";marketing_preference:number};
const safeCustomer=(c:CustomerRow)=>({id:c.id,email:c.email,firstName:c.first_name,lastName:c.last_name,phone:c.phone,address:c.address,subdistrict:c.subdistrict,district:c.district,province:c.province,postalCode:c.postal_code,status:c.status,emailVerifiedAt:c.email_verified_at,lastLoginAt:c.last_login_at,notificationFrequency:c.notification_frequency,marketingPreference:Boolean(c.marketing_preference)});
async function issueToken(connection: import("mysql2/promise").PoolConnection, customerId:number, purpose:"EMAIL_VERIFICATION"|"PASSWORD_RESET"|"EMAIL_CHANGE", pendingEmail?:string) { const raw=randomToken(); await connection.execute("UPDATE customer_action_tokens SET used_at=CURRENT_TIMESTAMP WHERE customer_id=? AND purpose=? AND used_at IS NULL",[customerId,purpose]); await connection.execute("INSERT INTO customer_action_tokens (customer_id,purpose,token_hash,pending_email,expires_at) VALUES (?,?,?,?,DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 30 MINUTE))",[customerId,purpose,tokenHash(raw),pendingEmail ?? null]); return raw; }
async function consumeToken(connection: import("mysql2/promise").PoolConnection, raw:string, purpose:"EMAIL_VERIFICATION"|"PASSWORD_RESET"|"EMAIL_CHANGE") { const [rows]=await connection.query<(RowDataPacket & {id:number;customer_id:number;pending_email:string|null})[]>("SELECT id,customer_id,pending_email FROM customer_action_tokens WHERE token_hash=? AND purpose=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP FOR UPDATE",[tokenHash(raw),purpose]); const row=rows[0]; if(!row) throw new ApiError(400,"This link is invalid or expired"); await connection.execute("UPDATE customer_action_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=?",[row.id]); return row; }
function requireCustomerMail() { if (env.NODE_ENV === "production" && !isMailConfigured()) throw new ApiError(503, "Email service is temporarily unavailable. Please try again later."); }
async function tryMail(send:()=>Promise<void>) { try { await send(); return true; } catch { return false; } }
export const customerAuthRoutes=Router(); customerAuthRoutes.use(requireSameOrigin);
customerAuthRoutes.post("/register",async(req,res,next)=>{try{requireCustomerMail();const data=registration.parse(req.body); const email=sanitizeEmail(data.email); const firstName=sanitizePlainText(data.firstName,80); const lastName=sanitizePlainText(data.lastName,80); const c=await withTransaction(async(connection)=>{const hash=await bcrypt.hash(data.password,12); const [result]=await connection.execute<ResultSetHeader>("INSERT INTO customer_accounts (email,password_hash,first_name,last_name,phone,status) VALUES (?,?,?,?,?,'PENDING_VERIFICATION')",[email,hash,firstName,lastName,data.phone ? sanitizePlainText(data.phone,40):null]); const id=Number(result.insertId); const raw=await issueToken(connection,id,"EMAIL_VERIFICATION"); return {id,raw};}); if(!await tryMail(()=>sendVerificationEmail(email,c.raw))){await withTransaction(connection=>connection.execute("DELETE FROM customer_accounts WHERE id=? AND status='PENDING_VERIFICATION'",[c.id]).then(()=>undefined));throw new ApiError(503,"Email service is temporarily unavailable. Please try again later.");} void tryMail(()=>sendRegistrationNotification({firstName,lastName,email,registeredAt:new Date().toISOString(),status:"PENDING_VERIFICATION"})); noStore(res); res.status(201).json({verificationRequired:true});}catch(e){next(e);}});
customerAuthRoutes.post("/login",async(req,res,next)=>{try{const data=credentials.parse(req.body); const rows=await queryRows<CustomerRow[]>("SELECT * FROM customer_accounts WHERE email=? LIMIT 1",[sanitizeEmail(data.email)]); const c=rows[0]; const valid=await bcrypt.compare(data.password,c?.password_hash ?? "$2a$12$Y3ww9pI95C8S7hWchm4xyu8Zy5ZcHMwY8S9wLPPpkBLeVqgZ8SpcK"); if(!c || c.status!=="ACTIVE" || !valid) throw new ApiError(401,"Invalid email or password"); const raw=await withTransaction(async(connection)=>{await connection.execute("UPDATE customer_accounts SET last_login_at=CURRENT_TIMESTAMP WHERE id=?",[c.id]); return createSession(connection,"customer",c.id);}); setSessionCookie(res,CUSTOMER_COOKIE,raw); noStore(res); res.json({customer:safeCustomer(c)});}catch(e){next(e);}});
customerAuthRoutes.post("/logout",requireCustomer,async(req,res,next)=>{try{const raw=readCookie(req.header("cookie"),CUSTOMER_COOKIE); await withTransaction(connection=>connection.execute("UPDATE customer_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=?",[tokenHash(raw ?? "")]).then(()=>undefined));clearSessionCookie(res,CUSTOMER_COOKIE);noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.post("/logout-all",requireCustomer,async(req,res,next)=>{try{await withTransaction(c=>revokeSessions(c,"customer",req.customer!.id));clearSessionCookie(res,CUSTOMER_COOKIE);noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.get("/session",async(req,res,next)=>{try{const token=readCookie(req.header("cookie"),CUSTOMER_COOKIE);if(!token)throw new ApiError(401,"Authentication required");const rows=await queryRows<CustomerRow[]>(`SELECT c.* FROM customer_sessions s JOIN customer_accounts c ON c.id=s.customer_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP LIMIT 1`,[tokenHash(token)]);const c=rows[0];if(!c||c.status!=="ACTIVE")throw new ApiError(401,"Authentication required");noStore(res);res.json({customer:safeCustomer(c)});}catch(e){next(e);}});
customerAuthRoutes.post("/verify-email",async(req,res,next)=>{try{const data=actionToken.parse(req.body);await withTransaction(async(c)=>{const t=await consumeToken(c,data.token,"EMAIL_VERIFICATION");await c.execute("UPDATE customer_accounts SET status='ACTIVE',email_verified_at=CURRENT_TIMESTAMP WHERE id=? AND status='PENDING_VERIFICATION'",[t.customer_id]);});noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.post("/resend-verification",async(req,res,next)=>{try{const data=z.object({email:z.string().email().max(190)}).strict().parse(req.body);const rows=await queryRows<CustomerRow[]>("SELECT * FROM customer_accounts WHERE email=? AND status='PENDING_VERIFICATION' LIMIT 1",[sanitizeEmail(data.email)]);const c=rows[0];let delivered=isMailConfigured();if(c&&delivered){const raw=await withTransaction(conn=>issueToken(conn,c.id,"EMAIL_VERIFICATION"));delivered=await tryMail(()=>sendVerificationEmail(c.email,raw));}noStore(res);res.json({ok:true,deliveryAvailable:delivered});}catch(e){next(e);}});
customerAuthRoutes.post("/forgot-password",async(req,res,next)=>{try{const data=z.object({email:z.string().email().max(190)}).strict().parse(req.body);const rows=await queryRows<CustomerRow[]>("SELECT * FROM customer_accounts WHERE email=? AND status='ACTIVE' LIMIT 1",[sanitizeEmail(data.email)]);const c=rows[0];let delivered=isMailConfigured();if(c&&delivered){const raw=await withTransaction(conn=>issueToken(conn,c.id,"PASSWORD_RESET"));delivered=await tryMail(()=>sendResetEmail(c.email,raw));}noStore(res);res.json({ok:true,deliveryAvailable:delivered});}catch(e){next(e);}});
customerAuthRoutes.post("/reset-password",async(req,res,next)=>{try{const data=reset.parse(req.body);await withTransaction(async(c)=>{const t=await consumeToken(c,data.token,"PASSWORD_RESET");await c.execute("UPDATE customer_accounts SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[await bcrypt.hash(data.password,12),t.customer_id]);await revokeSessions(c,"customer",t.customer_id);});clearSessionCookie(res,CUSTOMER_COOKIE);noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.post("/change-password",requireCustomer,async(req,res,next)=>{try{const data=changePassword.parse(req.body);const raw=await withTransaction(async(c)=>{const [rows]=await c.query<CustomerRow[]>("SELECT * FROM customer_accounts WHERE id=? FOR UPDATE",[req.customer!.id]);const user=rows[0];if(!user||!(await bcrypt.compare(data.currentPassword,user.password_hash)))throw new ApiError(401,"Current password is incorrect");if(await bcrypt.compare(data.newPassword,user.password_hash))throw new ApiError(400,"Choose a different password");await c.execute("UPDATE customer_accounts SET password_hash=? WHERE id=?",[await bcrypt.hash(data.newPassword,12),user.id]);await revokeSessions(c,"customer",user.id);return createSession(c,"customer",user.id);});setSessionCookie(res,CUSTOMER_COOKIE,raw);noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.post("/change-email",requireCustomer,async(req,res,next)=>{try{const data=changeEmail.parse(req.body);const newEmail=sanitizeEmail(data.newEmail);const token=await withTransaction(async(c)=>{const [rows]=await c.query<CustomerRow[]>("SELECT * FROM customer_accounts WHERE id=? FOR UPDATE",[req.customer!.id]);const user=rows[0];if(!user||!(await bcrypt.compare(data.currentPassword,user.password_hash)))throw new ApiError(401,"Current password is incorrect");if(user.email===newEmail)throw new ApiError(400,"Choose a different email address");const [existing]=await c.query<RowDataPacket[]>("SELECT id FROM customer_accounts WHERE email=? LIMIT 1 FOR UPDATE",[newEmail]);if(existing.length)throw new ApiError(400,"That email address is unavailable");return issueToken(c,user.id,"EMAIL_CHANGE",newEmail);});await tryMail(()=>sendEmailChangeEmail(newEmail,token));noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerAuthRoutes.post("/confirm-email-change",async(req,res,next)=>{try{const data=actionToken.parse(req.body);await withTransaction(async(c)=>{const token=await consumeToken(c,data.token,"EMAIL_CHANGE");if(!token.pending_email)throw new ApiError(400,"This link is invalid or expired");await c.execute("UPDATE customer_accounts SET email=?,email_verified_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",[token.pending_email,token.customer_id]);await revokeSessions(c,"customer",token.customer_id);});clearSessionCookie(res,CUSTOMER_COOKIE);noStore(res);res.json({ok:true});}catch(e){next(e);}});
export const customerRoutes=Router(); customerRoutes.use(requireSameOrigin,requireCustomer);
customerRoutes.get("/profile",async(req,res,next)=>{try{const rows=await queryRows<CustomerRow[]>("SELECT * FROM customer_accounts WHERE id=?",[req.customer!.id]);noStore(res);res.json({customer:safeCustomer(rows[0])});}catch(e){next(e);}});
customerRoutes.patch("/profile",async(req,res,next)=>{try{const data=profile.parse(req.body);const map:Record<string,string>={firstName:"first_name",lastName:"last_name",phone:"phone",address:"address",subdistrict:"subdistrict",district:"district",province:"province",postalCode:"postal_code"};const sets:string[]=[],values:(string|number|null)[]=[];for(const [key,column] of Object.entries(map)){if(data[key as keyof typeof data]!==undefined){sets.push(`${column}=?`);const value=data[key as keyof typeof data];values.push(value===null?null:sanitizePlainText(String(value),column==="address"?240:column==="phone"?40:column==="postal_code"?20:120));}}if(!sets.length)throw new ApiError(400,"No profile changes supplied");await withTransaction(c=>c.execute(`UPDATE customer_accounts SET ${sets.join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=?`,[...values,req.customer!.id]).then(()=>undefined));const rows=await queryRows<CustomerRow[]>("SELECT * FROM customer_accounts WHERE id=?",[req.customer!.id]);noStore(res);res.json({customer:safeCustomer(rows[0])});}catch(e){next(e);}});
customerRoutes.patch("/preferences",async(req,res,next)=>{try{const data=preferences.parse(req.body);await withTransaction(c=>c.execute("UPDATE customer_accounts SET notification_frequency=?,marketing_preference=? WHERE id=?",[data.notificationFrequency,data.marketingPreference?1:0,req.customer!.id]).then(()=>undefined));noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerRoutes.delete("/account",async(req,res,next)=>{try{const data=deleteAccount.parse(req.body);await withTransaction(async(c)=>{const [rows]=await c.query<CustomerRow[]>("SELECT * FROM customer_accounts WHERE id=? FOR UPDATE",[req.customer!.id]);if(!rows[0]||!(await bcrypt.compare(data.currentPassword,rows[0].password_hash)))throw new ApiError(401,"Current password is incorrect");await revokeSessions(c,"customer",req.customer!.id);await c.execute("UPDATE customer_accounts SET status='DELETED',email=CONCAT('deleted-',id,'-',email),password_hash='',updated_at=CURRENT_TIMESTAMP WHERE id=?",[req.customer!.id]);});clearSessionCookie(res,CUSTOMER_COOKIE);noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerRoutes.get("/favorites",async(req,res,next)=>{try{const rows=await queryRows<(RowDataPacket&{listing_id:number})[]>(`SELECT f.listing_id FROM customer_favorites f JOIN listings l ON l.id=f.listing_id WHERE f.customer_id=? AND l.status='PUBLISHED' ORDER BY f.created_at DESC`,[req.customer!.id]);noStore(res);res.json({propertyIds:rows.map(r=>String(r.listing_id))});}catch(e){next(e);}});
customerRoutes.put("/favorites/:propertyId",async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.propertyId);await withTransaction(async(c)=>{const [listing]=await c.query<(RowDataPacket&{id:number})[]>("SELECT id FROM listings WHERE id=? AND status='PUBLISHED' LIMIT 1",[id]);if(!listing[0])throw new ApiError(404,"Property not found");await c.execute("INSERT IGNORE INTO customer_favorites (customer_id,listing_id) VALUES (?,?)",[req.customer!.id,id]);});noStore(res);res.json({ok:true});}catch(e){next(e);}});
customerRoutes.delete("/favorites/:propertyId",async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.propertyId);await withTransaction(c=>c.execute("DELETE FROM customer_favorites WHERE customer_id=? AND listing_id=?",[req.customer!.id,id]).then(()=>undefined));noStore(res);res.json({ok:true});}catch(e){next(e);}});
